// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH-bxAMAasjxVKf_QyKRMdIoEnMje4zs8',
    appId: '1:861096291156:web:1e7b29f12fd2fa3dbb36c1',
    messagingSenderId: '861096291156',
    projectId: 'bank-query-bot',
    authDomain: 'bank-query-bot.firebaseapp.com',
    storageBucket: 'bank-query-bot.firebasestorage.app',
    measurementId: 'G-S8PPGM49YK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABCKiTSfFILO_rg8ygde744o6_sWzlbPM',
    appId: '1:861096291156:android:ce5c139a48512de2bb36c1',
    messagingSenderId: '861096291156',
    projectId: 'bank-query-bot',
    storageBucket: 'bank-query-bot.firebasestorage.app',
  );
}
